# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack_headers}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Daigle"]
  s.date = %q{2009-11-19}
  s.email = %q{ryan@digitaltoniq.com}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "lib/rack_headers.rb",
     "lib/rack_headers/print.rb",
     "rack_headers.gemspec"
  ]
  s.homepage = %q{http://github.com/digitaltoniq/rack-headers}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rack middleware to output the state of your request/response headers}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

